version: '3.8'  # Specifica la versione del file Compose

services:
  keycloak_hospital:
    container_name: hospital-container
    image: quay.io/keycloak/keycloak:22.0.3  # Repository dell'immagine di Keycloak
    command: start-dev  # Comando per avviare Keycloak in modalità di sviluppo
    environment:  # Variabili d'ambiente per la configurazione di Keycloak
      KC_HOSTNAME: localhost  # Nome host
      KC_HOSTNAME_PORT: 8080  # Porta
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT_HTTPS: 'false'  # Configurazione per HTTP
      KC_HEALTH_ENABLED: 'true'  # Abilita il controllo di salute

      # Credenziali amministratore per accedere a Keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8080"

      # Configurazione del database per Keycloak
      KC_DB: postgres  # Tipo di database utilizzato
      KC_DB_URL_HOST: postgres_keycloak_hospital  # Nome host del database
      KC_DB_URL_DATABASE: hospital  # Nome del database
      KC_DB_URL_USERNAME: keycloak  # Nome utente del database
      KC_DB_PASSWORD: password  # Password del database
      KC_DB_SCHEMA: public  # Schema del database

    ports:
      - "8080:8080"  # Mappa la porta 8080 del contenitore alla porta 8080 della macchina host
    restart: always  # Riavvia il contenitore automaticamente
    depends_on:
      postgres_keycloak_hospital:
        condition: service_healthy  # Aspetta che il servizio Postgres sia sano
    networks:
      - keycloak_hospital_dev_network  # Rete personalizzata per Keycloak

  postgres_keycloak_hospital:
    image: postgres:16  # Immagine per il server PostgreSQL
    command: postgres -c 'max_connections=200'  # Configura il numero massimo di connessioni
    volumes:
      - /var/lib/postgresql/data  # Percorso per l'archiviazione persistente dei dati del database
    environment:  # Configurazione per il database Postgres
      POSTGRES_DB: hospital  # Nome del database
      POSTGRES_USER: keycloak  # Nome utente
      POSTGRES_PASSWORD: password  # Password
    healthcheck:
      test: "exit 0"  # Test di salute semplificato
    ports:
      - "5432:5432"  # Mappa la porta 5432 del contenitore alla porta 5432 della macchina host
    networks:
      - keycloak_hospital_dev_network  # Rete per PostgreSQL

  mongodb:
    image: mongo:latest  # Immagine per MongoDB
    container_name: mongo_container  # Nome del contenitore MongoDB
    ports:
      - "27018:27017"  # Mappa la porta 27017 del contenitore alla porta 27017 della macchina host
    volumes:
      - mongo_data:/data/db  # Volume per la persistenza dei dati di MongoDB
    networks:
      - keycloak_hospital_dev_network  # Rete condivisa

volumes:
  mongo_data:  # Dichiarazione del volume per MongoDB
  pdgdata_keycloak_hospital:  # Volume per il database Keycloak

networks:
  keycloak_hospital_dev_network:
    driver: bridge  # Tipo di rete utilizzata
